### ISSUE TITLE
前端安装依赖冲突

### ISSUE THREAD

**Issue by MiderWong** [trueleaf/moyu#10]
安装时报错，报错信息如下：
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: moyu@0.8.0
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.29.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.15
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"~4.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
使用`npm install --force`安装成功，希望解决一下。

**Comment by MiderWong** [comment]
接上，系统环境如下：
```
OS：MacOS Monterey(12.0.1)
NodeJS：v14.18.1
npm: 8.1.4
```
每次安装都会卡在`cypress`这里，最后成功安装过程如下：
##### 1、在`package.json`中删除`"@vue/cli-plugin-e2e-cypress": "~4.5.0",`的引用；
##### 2、执行`npm install --force`；
##### 3、访问链接`https://download.cypress.io/desktop/3.8.3?platform=darwin&arch=x64`下载`cypress`；
##### 4、执行`set CYPRESS_INSTALL_BINARY=~/Downloads/cypress.zip & npm install cypress@3.8.3`安装`cypress`；
##### 5、在`package.json`中添加`"@vue/cli-plugin-e2e-cypress": "~4.5.0",`的引用；
##### 6、执行`npm i @vue/cli-plugin-e2e-cypress@4.5.0`安装`@vue/cli-plugin-e2e-cypress`。

**Comment by MiderWong** [comment]
接上，安装教程参考的是`https://www.yuque.com/happymoyu/as0gig/vapwmq`，版本我用的是`master`分支，没有修改配置中的任何内容，都使用的是在线服务器，我只想先把客户端跑起来。
安装扩展之后执行`npm run dev`提示如下错误：
```
➜  moyu git:(master) ✗ npm run dev

> moyu@0.8.0 dev
> vue-cli-service electron:serve

 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'NormalModule' of undefined
TypeError: Cannot read property 'NormalModule' of undefined
    at VueLoaderPlugin.apply (/Volumes/ShareData/wwwroot/moyu/node_modules/vue-loader-v16/dist/pluginWebpack5.js:44:47)
    at webpack (/Volumes/ShareData/wwwroot/moyu/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/Volumes/ShareData/wwwroot/moyu/node_modules/@vue/cli-service/lib/commands/serve.js:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Volumes/ShareData/wwwroot/moyu/node_modules/vue-cli-plugin-electron-builder/index.js:299:22
```
无奈了。

**Comment by shuxiaokai3** [comment]
> 接上，安装教程参考的是`https://www.yuque.com/happymoyu/as0gig/vapwmq`，版本我用的是`master`分支，没有修改配置中的任何内容，都使用的是在线服务器，我只想先把客户端跑起来。 安装扩展之后执行`npm run dev`提示如下错误：
> 
> ```
> ➜  moyu git:(master) ✗ npm run dev
> 
> > moyu@0.8.0 dev
> > vue-cli-service electron:serve
> 
>  INFO  Starting development server...
>  ERROR  TypeError: Cannot read property 'NormalModule' of undefined
> TypeError: Cannot read property 'NormalModule' of undefined
>     at VueLoaderPlugin.apply (/Volumes/ShareData/wwwroot/moyu/node_modules/vue-loader-v16/dist/pluginWebpack5.js:44:47)
>     at webpack (/Volumes/ShareData/wwwroot/moyu/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:51:13)
>     at serve (/Volumes/ShareData/wwwroot/moyu/node_modules/@vue/cli-service/lib/commands/serve.js:163:22)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async /Volumes/ShareData/wwwroot/moyu/node_modules/vue-cli-plugin-electron-builder/index.js:299:22
> ```
> 
> 无奈了。

因为国内网络的一些关系，建议您这边尝试：移除已有的node_modules和package.lock.json,

1. 通过yarn来安装， 安装同时将yarn的源设置为国内的镜像
yarn config set registry https://registry.npm.taobao.org
yarn install
2. 通过cnpm来安装

在windows系统上，npm安装也会出现您这边描述的错误，可以尝试使用yarn或者cnpm
mac系统上面测试会少一些，这边会尽快帮你测试mac系统上面安装错误

**Comment by MiderWong** [comment]
恩，网速慢的问题我知道，我现在都用的是国内镜像，好在所需扩展都安装成功了。目前只构建了Windows版本，macOS版本还未构建对吗？

**Comment by shuxiaokai3** [comment]
> 恩，网速慢的问题我知道，我现在都用的是国内镜像，好在所需扩展都安装成功了。目前只构建了Windows版本，macOS版本还未构建对吗？

您这边是通过yarn或者cnpm解决刚刚的问题吗
mac版本还未构建过，windows和linux都可以正常构建

**Comment by MiderWong** [comment]
三个问题：
1、依赖冲突未解决，使用`--force`安装依赖，可以安装成功，但并未解决冲突问题；
2、我用的是`cnpm`，但依然没解决`cypress`安装问题，解决方法是通过下载离线安装包，设置环境变量安装，这个问题与程序代码无关；
3、依赖安装成功后，执行`npm run dev/build`都会提示`Cannot read property 'NormalModule' of undefined`的错误。

所以综上所述，不要关注`cypress`的安装问题和`cnpm`的问题，依赖都安装完成了，需要关注的是①、和③的依赖冲突问题和mac下运行、打包时的错误问题。

**Comment by shuxiaokai3** [comment]
感谢您的反馈，我们将会在最近尝试修复您提到的问题，有最新进展会在当前issue及时反馈

**Comment by MiderWong** [comment]
好的，多谢，辛苦，开源不易。🌹

**Comment by shuxiaokai3** [comment]
1. 安装包依赖冲突问题已解决 (移除了html-webpack-plugins)
2. 移除了cypress相关内容
3. 修复了Cannot read property 'NormalModule' of undefined，这个也是html-webpack-plugins安装包导致的问题
4. Windows10和Mac环境下都能正确运行与打包项目，我们更新了部分部署文档，同时修复了一些依赖版本问题
5. 我们在release中提供Mac版本下载
6. 目前测试的node版本为 14~16，操作系统 Windows10 & MacOS Monterey(12.0.1)
7. 您可以拉取最新代码来解决之前的问题


我们预计会在除夕前发布第一个稳定版本，感谢您对项目的支持与关注！🌹

**Comment by MiderWong** [comment]
效率真高，点赞，我尝试一下，🌹！

**Comment by MiderWong** [comment]
我来反馈了
### 1、部署文档的一处小瑕疵
文档链接在：[产品和开发文档(快乐摸鱼)](https://www.yuque.com/happymoyu/as0gig/vapwmq#Cti7h) 客户端更新配置章节，瑕疵如下图：
![image](https://user-images.githubusercontent.com/7487008/143669222-c2620942-6cd9-45b5-a5f8-29c7466b3c5b.png)

### 2、本地`Web`版部署效果
由于想同时测试`Web`版本，我在本地执行了`npm run build`并部署至`Nginx`，
所做的配置修改如下：
```
//主进程配置
    mainConfig: {
        useLocalFile: true, //使用本地文件作为主进程加载内容
    },
//本地部署相关配置
    localization: {
        enableRegister: false, //是否允许注册
        enableGuest: false, //是否允许来宾用户体验
        enableDocLink: false, //是否显示文档和帮助链接
    },
```
请原谅我，把`文档和帮助链接`也隐藏了。说一下我的使用场景：

- 内网
- 管理员添加账号
- 不允许个人以任何方式注册，包括手机、邮箱等注册手段
- 后台添加账号时使用邮箱作为账号
- 未来可能允许邮箱找回密码

> 说明：体验较浅，且还未部署后台体验，只说场景，待前后台全部本地部署后继续做反馈。

部署效果如下：
![image](https://user-images.githubusercontent.com/7487008/143668977-aaaf2b7a-367c-4a10-9d2d-5d6b69627ee4.png)

> 右边`忘记密码`错位的原因已找到，我禁用了`允许注册`和`来宾用户体验`以后，右侧登录入口面板缺少了`直接登录`和`注册账号`入口，而代码文件`moyu/src/renderer/pages/login/components/login-account.vue`中的`.forget-pwd-wrap`元素的`margin-top`属性的`-20px`的值是写死的，所以在缺失了两个支撑元素之后就错位了。

### 3、客户端部署
`MacOS Monterey 12.0.1`版本成功打包，效果与`Web`版效果一致，赞一个。👍🏻

### 4、修改建议
- 建议登录页面左侧加入演示视频或者图片效果或者`Logo`，并加入是否隐藏的配置；
- 建议登录页面`客户端下载文字`与底部`平台Logo和下载链接`不要割裂，作为一个整体；
- 若可以隐藏推广内容，甚至可以将客户端下载入口放在登录框底部原来`文档和帮助`的位置
以上是几点吹毛求疵的与业务功能无关的小建议，修改与否都无关紧要，待我部署完服务端体验之后继续反馈。

谢谢开发者。

**Comment by MiderWong** [comment]
本地服务端部署成功了，接着反馈：
#### 1、运行时的问题
客户端可以运行成功，但是运行过程中有如下提示：
```
INFO  Launching Electron...
(node:85871) ExtensionLoadWarning: Warnings loading extension at /Users/mider/Library/Application Support/moyu/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:85871) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from undefined
    at Function.n.fromId (electron/js2c/browser_init.js:33:1314)
    at update (webpack:///./src/main/update.ts?:33:68)
    at _callee$ (webpack:///./src/main/background.ts?:136:66)
    at tryCatch (webpack:///./node_modules/regenerator-runtime/runtime.js?:96:17)
    at Generator.invoke [as _invoke] (webpack:///./node_modules/regenerator-runtime/runtime.js?:310:22)
    at Generator.eval [as next] (webpack:///./node_modules/regenerator-runtime/runtime.js?:148:21)
    at asyncGeneratorStep (webpack:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js?:9:24)
    at _next (webpack:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js?:31:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:85871) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:85871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:85880) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
### 2、左侧导航部分
![image](https://user-images.githubusercontent.com/7487008/143674025-3b7a3460-7ffe-4cfc-b3bc-dffced457ccb.png)
`历史记录`和`全局设置`两个功能都无法使用。
### 3、环境维护问题
环境维护中添加的环境，修改后，在接口页面无法同时生效，刷新也不行。举例如下图：
![image](https://user-images.githubusercontent.com/7487008/143675094-ae3aac6b-377d-4d60-9e68-3056b8adc7e7.png)
![image](https://user-images.githubusercontent.com/7487008/143675097-2383c4de-7c43-42f9-8a63-b806933f0601.png)
### 4、保存接口时提示错误
错误效果如下：
![image](https://user-images.githubusercontent.com/7487008/143674925-a855916a-0ba1-4b3a-8bd7-6d15d9d0aaf2.png)
### 5、导出文档配置
导出文档如何配置，我进行如下配置后无法使用导出的文档：
```
//导出文档相关配置
share: {
    // baseUrl: "https://share.jobtool.cn",
    baseUrl: "http//127.0.0.1:7004"
},
```
### 6、导出文档问题
#### ①、`导出文档`为`HTML`后，如果使用代理发起请求会提示`set-cookie`问题，提示：`Cannot read properties of undefined (reading 'set-cookie')`，如果不使用代理，则提示`Error: Network Error`；
#### ②、使用代理发起请求后，`发送请求`按钮会隐藏，或许是请求没有发送成功的原因？对比效果如下图：
![image](https://user-images.githubusercontent.com/7487008/143676542-8400d70a-173a-42e2-af66-f2c3f793752c.png)

![image](https://user-images.githubusercontent.com/7487008/143676474-749cc791-ed23-4b70-ba8b-f5ad7fec816d.png)
### 7、改进建议
#### ①、文件夹加入`命名空间`概念
我不知道数据结构什么样，改动会有多大，只是一个小建议，举例子，我的接口地址：
`http://gymoo.local.test/v1/app/regionlist?level=1`，其中`v1`是版本号，`app`是对应的平台，`regionlist`是对应的接口入口，分别通过`get`、`post`、`put`、`delete`协议提供增删改查功能，如果有`命名空间`概念，则文件夹名称为显示名称，命名空间为接口地址拼接属性，当然，如果实现了`命名空间`，整体接口效果能影响的地方就太多了，可做参考，具体效果如下图所示：
![image](https://user-images.githubusercontent.com/7487008/143675932-1f27fb72-ccee-4ce3-bb57-9b2ffaa12595.png)
#### ②、接口参数处理
请求头中的默认自带常用参数功能，太👍🏻了，其它一些小建议：
- [ ] 返回参数为`json`格式时，支持参数导入(这样会很方便)
- [ ] `Params`的导入解析(难度会有些大吧，只是建议)
- [ ] 接口备注信息可以允许添加、编辑
- [ ] 发送请求后的返回值可以做一下美化，现在是一行到底
- [ ] `编辑`和`预览`模式的模式标识，由于在预览模式下，`回收站`、`导出文档`、`导入文档`功能都不能用，让我以为很多功能都没做

以上就是简单的接口功能本身的使用时我遇到的问题，至于后台权限管理我简单看了下，除了邮箱问题之外，其它的暂时没有什么需求，但是邮箱问题可以最后解决或者不解决都没关系，接口文档使用问题和建议，你们可以看看❤️。

如果可以的话，咱们可以互留联系方式直接联系。

**Comment by shuxiaokai3** [comment]
今天周末回复的有点晚，这是我的qq：3073155898，wx：shu_xiao_kai  看您这边方便呢！我们会尽快处理您这边的问题。

**Comment by MiderWong** [comment]
好，加你wx了。

**Comment by shuxiaokai3** [comment]
依赖冲突问题在最新版本中已经解决
